export default function Head() {
    return (
        <>
            <title>HonkaiLog</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" type="image/png" href="/favicon.png"/>
            <meta charSet="utf-8"></meta>
        </>
    )
}
