export default function Head() {
    return (
        <>
            <title>HonkaiLog</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/public/favicon.ico"/>
            <meta charSet="utf-8"></meta>
        </>
    )
}
